# Generated by Django 3.1.1 on 2020-11-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone', phone_field.models.PhoneField(blank=True, default='', max_length=31, null=True)),
                ('major', models.CharField(choices=[('', ''), ('Aerospace Engineering', 'Aerospace Engineering'), ('African American and African Studies', 'African American and African Studies'), ('American Studies', 'American Studies'), ('Anthropology', 'Anthropology'), ('Archaeology', 'Archaeology'), ('Architectural History', 'Architectural History'), ('Architecture', 'Architecture'), ('Astronomy', 'Astronomy'), ('Bachelor of Interdisciplinary Studies', 'Bachelor of Interdisciplinary Studies'), ('Bachelor of Professional Studies in Health Sciences Management', 'Bachelor of Professional Studies in Health Sciences Management'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Classics', 'Classics'), ('Cognitive Science', 'Cognitive Science'), ('Commerce', 'Commerce'), ('Comparative Literature', 'Comparative Literature'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science (B.A.)', 'Computer Science (B.A.)'), ('Computer Science (B.S.)', 'Computer Science (B.S.)'), ('Dance', 'Dance'), ('Drama', 'Drama'), ('East Asian Languages, Literatures and Culture', 'East Asian Languages, Literatures and Culture'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Engineering Science', 'Engineering Science'), ('English', 'English'), ('Environmental Sciences', 'Environmental Sciences'), ('Environmental Thought and Practice', 'Environmental Thought and Practice'), ('Five-Year Teacher Education Program', 'Five-Year Teacher Education Program'), ('French', 'French'), ('German', 'German'), ('German Studies', 'German Studies'), ('Global Studies', 'Global Studies'), ('Global Sustainability Minor', 'Global Sustainability Minor'), ('Historic Preservation Minor', 'Historic Preservation Minor'), ('History', 'History'), ('History of Art', 'History of Art'), ('Human Biology', 'Human Biology'), ('Interdisciplinary Major of Global Studies', 'Interdisciplinary Major of Global Studies'), ('Jewish Studies', 'Jewish Studies'), ('Kinesiology (BSEd)', 'Kinesiology (BSEd)'), ('Landscape Architecture Minor', 'Landscape Architecture Minor'), ('Latin American Studies', 'Latin American Studies'), ('Linguistics', 'Linguistics'), ('Materials Science and Engineering', 'Materials Science and Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Media Studies', 'Media Studies'), ('Medieval Studies', 'Medieval Studies'), ('Middle Eastern and South Asian Languages and Cultures', 'Middle Eastern and South Asian Languages and Cultures'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political and Social Thought', 'Political and Social Thought'), ('Political Philosophy, Policy, and Law', 'Political Philosophy, Policy, and Law'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Religious Studies', 'Religious Studies'), ('Slavic Languages and Literatures', 'Slavic Languages and Literatures'), ('Sociology', 'Sociology'), ('Spanish', 'Spanish'), ('Speech Communication Disorders', 'Speech Communication Disorders'), ('Statistics', 'Statistics'), ('Studio Art', 'Studio Art'), ('Systems Engineering', 'Systems Engineering'), ('Urban and Environmental Planning', 'Urban and Environmental Planning'), ('Women, Gender & Sexuality', 'Women, Gender & Sexuality'), ('Youth & Social Innovation (BSEd)', 'Youth & Social Innovation (BSEd)')], default='', max_length=255, null=True)),
                ('minor', models.CharField(blank=True, choices=[('', ''), ('Aerospace Engineering', 'Aerospace Engineering'), ('African American and African Studies', 'African American and African Studies'), ('American Studies', 'American Studies'), ('Anthropology', 'Anthropology'), ('Archaeology', 'Archaeology'), ('Architectural History', 'Architectural History'), ('Architecture', 'Architecture'), ('Astronomy', 'Astronomy'), ('Bachelor of Interdisciplinary Studies', 'Bachelor of Interdisciplinary Studies'), ('Bachelor of Professional Studies in Health Sciences Management', 'Bachelor of Professional Studies in Health Sciences Management'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Classics', 'Classics'), ('Cognitive Science', 'Cognitive Science'), ('Commerce', 'Commerce'), ('Comparative Literature', 'Comparative Literature'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science (B.A.)', 'Computer Science (B.A.)'), ('Computer Science (B.S.)', 'Computer Science (B.S.)'), ('Dance', 'Dance'), ('Drama', 'Drama'), ('East Asian Languages, Literatures and Culture', 'East Asian Languages, Literatures and Culture'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Engineering Science', 'Engineering Science'), ('English', 'English'), ('Environmental Sciences', 'Environmental Sciences'), ('Environmental Thought and Practice', 'Environmental Thought and Practice'), ('Five-Year Teacher Education Program', 'Five-Year Teacher Education Program'), ('French', 'French'), ('German', 'German'), ('German Studies', 'German Studies'), ('Global Studies', 'Global Studies'), ('Global Sustainability Minor', 'Global Sustainability Minor'), ('Historic Preservation Minor', 'Historic Preservation Minor'), ('History', 'History'), ('History of Art', 'History of Art'), ('Human Biology', 'Human Biology'), ('Interdisciplinary Major of Global Studies', 'Interdisciplinary Major of Global Studies'), ('Jewish Studies', 'Jewish Studies'), ('Kinesiology (BSEd)', 'Kinesiology (BSEd)'), ('Landscape Architecture Minor', 'Landscape Architecture Minor'), ('Latin American Studies', 'Latin American Studies'), ('Linguistics', 'Linguistics'), ('Materials Science and Engineering', 'Materials Science and Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Media Studies', 'Media Studies'), ('Medieval Studies', 'Medieval Studies'), ('Middle Eastern and South Asian Languages and Cultures', 'Middle Eastern and South Asian Languages and Cultures'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political and Social Thought', 'Political and Social Thought'), ('Political Philosophy, Policy, and Law', 'Political Philosophy, Policy, and Law'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Religious Studies', 'Religious Studies'), ('Slavic Languages and Literatures', 'Slavic Languages and Literatures'), ('Sociology', 'Sociology'), ('Spanish', 'Spanish'), ('Speech Communication Disorders', 'Speech Communication Disorders'), ('Statistics', 'Statistics'), ('Studio Art', 'Studio Art'), ('Systems Engineering', 'Systems Engineering'), ('Urban and Environmental Planning', 'Urban and Environmental Planning'), ('Women, Gender & Sexuality', 'Women, Gender & Sexuality'), ('Youth & Social Innovation (BSEd)', 'Youth & Social Innovation (BSEd)')], default='', max_length=255, null=True)),
                ('graduation', models.CharField(choices=[('', ''), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Answer', 'Prefer Not to Answer')], default='', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(default='', max_length=255, null=True)),
                ('group_zoom_link', models.URLField(default='', max_length=255, null=True)),
                ('friends', models.ManyToManyField(blank=True, to='finder.Profile')),
                ('group_members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=255, null=True)),
                ('group_zoom_link', models.CharField(default='', max_length=255, null=True)),
                ('members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='finder.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
