# Generated by Django 3.1.1 on 2020-10-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
