# Generated by Django 3.1.1 on 2020-10-16 06:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20201016_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
