# Generated by Django 3.1.1 on 2020-10-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20201016_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
