# Generated by Django 3.1.1 on 2020-10-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_auto_20201018_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
