# Generated by Django 3.1.1 on 2020-10-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0013_auto_20201019_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
