# Generated by Django 3.1.1 on 2020-10-20 02:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0017_auto_20201019_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='', max_length=31, null=True),
        ),
    ]
