# Generated by Django 3.1.1 on 2020-10-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0018_auto_20201019_2245'),
        ('finder', '0015_auto_20201019_0441'),
    ]

    operations = [
    ]
